name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CUDACXX: /usr/local/cuda/bin/nvcc

jobs:
  build: 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: apt update
      run: apt update -y && apt upgrade -y
        
    - name: Build from src
      run: mkdir build && cd build && cmake -DBUILD_COVERAGE=1 .. && make  -j8
      
    - name: set PYTHONPATH
      run: echo PYTHONPATH=/gnina-runner/_work/gnina/gnina/build/external/lib/python3.8/site-packages/ >> $GITHUB_ENV
      
    - name: install gnina
      run: cd build && make install
      
    - name: Run tests 
      continue-on-error: true 
      run: cd build && ctest --timeout 7200 && ctest -T Coverage
      
    - name: Upload code coverage
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
